- type: entity
  parent: MobHuman
  id: N14MobHumanBoSWashingtonPaladin
  setPreference: false #LL
  name: BoSWashingtonPaladin
  components:
    - type: Icon
      sprite: _Nuclear14/Markers/Jobs/boswashington.rsi
      state: paladin
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [BoSWashingtonPaladinGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - BrotherhoodWashington

- type: entity
  parent: N14MobHumanBoSWashingtonPaladin
  id: N14MobHumanBoSWashingtonCommander
  setPreference: false #LL
  name: BoSWashingtonCommander
  components:
    - type: Icon
      state: commander
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [BoSWashingtonCommanderGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - BrotherhoodWashington

- type: entity
  parent: N14MobHumanBoSWashingtonPaladin
  id: N14MobHumanBoSWashingtonInitiate
  setPreference: false #LL
  name: BoSWashingtonInitiate
  components:
    - type: Icon
      state: initiate
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [BoSWashingtonInitiateGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - BrotherhoodWashington

- type: entity
  parent: N14MobHumanBoSWashingtonPaladin
  id: N14MobHumanBoSWashingtonScribe
  setPreference: false #LL
  name: BoSWashingtonScribe
  components:
    - type: Icon
      state: scribe
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [BoSWashingtonScribeGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - BrotherhoodWashington

- type: entity
  parent: N14MobHumanBoSWashingtonPaladin
  id: N14MobHumanBoSWashingtonKnight
  setPreference: false #LL
  name: BoSWashingtonKnight
  components:
    - type: Icon
      state: knight
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [BoSWashingtonKnightGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - BrotherhoodWashington

