- type: entity
  parent: MobHuman
  id: N14MobHumanRaider
  setPreference: false #LL
  name: Raider
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [RaiderGear]
    - type: NpcFactionMember
      factions:
      - Raider
