- type: department
  id: CaesarLegion
  description: department-CaesarLegion-description
  color: "#950202"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Raider
  description: department-Raider-description
  color: "#093f09"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: BrotherhoodWest
  description: department-BrotherhoodWest-description
  color: "#0c0fb1"
  roles: []
  available: false
  editorHidden: true
