- type: entity
  parent: N14MobHumanFollowers
  id: LLMobHumanMetroResident
  name: Житель Метро
  components:
    - type: Icon
      state: MetroResident
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [LLMetroResident]
    - type: NpcFactionMember
      factions:
      - Metro

- type: entity
  parent: N14MobHumanFollowers
  id: LLMobHumanMachinist
  name: Машинист
  components:
    - type: Icon
      state: MetroResident
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [LLMachinist]
    - type: NpcFactionMember
      factions:
      - Metro

- type: entity
  parent: N14MobHumanFollowers
  id: LLMobHumanBastard
  name: Ублюдок
  components:
    - type: Icon
      state: MetroResident
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [LLBastard]
    - type: NpcFactionMember
      factions:
      - Bandit
