- type: entity
  id: SpawnPointMetroResident
  parent: SpawnPointJobBase
  name: Житель Метро
  components:
  - type: SpawnPoint
    job_id: MetroResident
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointMachinist
  parent: SpawnPointJobBase
  name: Машинист
  components:
  - type: SpawnPoint
    job_id: Machinist
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointBastard
  parent: SpawnPointJobBase
  name: Ублюдок
  components:
  - type: SpawnPoint
    job_id: Bastard
  - type: Sprite
    layers:
      - state: green
      - state: passenger
