# Top-down, highest to lowest rank when possible.
- type: department
  id: BrotherhoodMidwest
  description: department-BrotherhoodMidwest-description
  color: "#3B72BF"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: BrotherhoodWashington
  description: department-BrotherhoodWashington-description
  color: "#a2000f"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: CaravanCompany
  description: department-CaravanCompany-description
  color: "#a1887f"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: NCR
  description: department-NCR-description
  color: "#fbc02d"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Rangers
  description: department-Ranger-description
  color: "#3ab700"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Tribe
  description: department-Tribe-description
  color: "#d69b3d"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Vault
  description: department-Vault-description
  color: "#0d47a1"
  roles:
  - Overseer
  - VaultSecurity
  - VaultDoctor
  - VaultEngineer
  - VaultDweller

- type: department
  id: Wastelander
  description: department-Wastelander-description
  color: "#81c784"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Townsfolk
  description: department-Townsfolk-description
  color: "#5c733a"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Zetan
  description: department-Zetan-description
  color: "#7ec133"
  roles: []
  available: false
  editorHidden: true

- type: department
  id: Followers
  description: department-Followers-description
  color: "#33a1c1"
  roles: []
  available: false
  editorHidden: true
